name: Build & Deploy Product Microservice
on:
  push:
    branches:
      - add-deploying-and-building-file
  pull_request:
    branches:
      - add-deploying-and-building-file

jobs:
  build-deploy:
    name: Build and Deploy Product Microservice
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 23
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto' # Use Corretto distribution
          java-version: 23         # Use Java 21 (latest non-LTS version)

      - name: Run Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run: mvn clean package --file pom.xml
