name: Build & Deploy product microservice

on:
  push:
    branches:
      - add-deploying-and-building-file
  pull_request:
    branches:
      - add-deploying-and-building-file
jobs:
  build-deploy:
    name: Build and Deploy product
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup jdk 23
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 23

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run:
          mvn clean
          mvn -B package --file pom.xml

