name: Build & Deploy product microservice

on:
  push:
    branches:
      - main

jobs:
  build-deploy:
    name: Build and Deploy product
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: admin
          POSTGRES_DB: productDatabase
        ports:
          - 5432:5432
        options: >-
          --health-cmd "pg_isready -U user" 
          --health-interval 10s 
          --health-timeout 5s 
          --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup jdk 23
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: 23

      - name: Unit Tests
        run: mvn -B test --file pom.xml

      - name: Build the application
        run:
          mvn clean
          mvn -B package --file pom.xml

